// AUTO-GENERATED by Supabase MCP. Do not edit by hand.
// Regenerate via: mcp__supabase__generate_typescript_types

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[]

export type Database = {
  // Allows to automatically instantiate createClient with right options
  // instead of createClient<Database, { PostgrestVersion: 'XX' }>(URL, KEY)
  __InternalSupabase: {
    PostgrestVersion: "14.1"
  }
  public: {
    Tables: {
      audit_log: {
        Row: {
          action: string
          actor_id: string | null
          change_summary: string | null
          created_at: string | null
          entity_id: string | null
          entity_type: string
          log_id: string
          new_values: Json | null
          old_values: Json | null
        }
        Insert: {
          action: string
          actor_id?: string | null
          change_summary?: string | null
          created_at?: string | null
          entity_id?: string | null
          entity_type: string
          log_id?: string
          new_values?: Json | null
          old_values?: Json | null
        }
        Update: {
          action?: string
          actor_id?: string | null
          change_summary?: string | null
          created_at?: string | null
          entity_id?: string | null
          entity_type?: string
          log_id?: string
          new_values?: Json | null
          old_values?: Json | null
        }
        Relationships: []
      }
      call_events: {
        Row: {
          call_id: string
          created_at: string | null
          customer_phone: string | null
          dealer_code: number | null
          dealer_id: string | null
          direction: string | null
          disposition_code: string | null
          duration: number | null
          end_time: string | null
          feedback_data: Json | null
          is_productive: boolean | null
          kam_id: string | null
          lead_id: string | null
          notes: string | null
          outcome: string | null
          start_time: string
        }
        Insert: {
          call_id?: string
          created_at?: string | null
          customer_phone?: string | null
          dealer_code?: number | null
          dealer_id?: string | null
          direction?: string | null
          disposition_code?: string | null
          duration?: number | null
          end_time?: string | null
          feedback_data?: Json | null
          is_productive?: boolean | null
          kam_id?: string | null
          lead_id?: string | null
          notes?: string | null
          outcome?: string | null
          start_time: string
        }
        Update: {
          call_id?: string
          created_at?: string | null
          customer_phone?: string | null
          dealer_code?: number | null
          dealer_id?: string | null
          direction?: string | null
          disposition_code?: string | null
          duration?: number | null
          end_time?: string | null
          feedback_data?: Json | null
          is_productive?: boolean | null
          kam_id?: string | null
          lead_id?: string | null
          notes?: string | null
          outcome?: string | null
          start_time?: string
        }
        Relationships: []
      }
      dashboard_layouts: {
        Row: {
          created_at: string
          dashboard_key: string
          display_name: string
          enabled: boolean
          layout_id: string
          role: string
          tiles: Json
          updated_at: string
          updated_by: string | null
          version: number
        }
        Insert: {
          created_at?: string
          dashboard_key: string
          display_name: string
          enabled?: boolean
          layout_id: string
          role: string
          tiles: Json
          updated_at?: string
          updated_by?: string | null
          version?: number
        }
        Update: {
          created_at?: string
          dashboard_key?: string
          display_name?: string
          enabled?: boolean
          layout_id?: string
          role?: string
          tiles?: Json
          updated_at?: string
          updated_by?: string | null
          version?: number
        }
        Relationships: []
      }
      dcf_leads_master: {
        Row: {
          approval_date: string | null
          approval_date_clean: string | null
          asm_mapping: string | null
          banking_flag: string | null
          banking_required: number | null
          buyback: number | null
          case_status: string | null
          case_status_2: string | null
          cc_fos: string | null
          cc_fos_2: string | null
          cc_sm: string | null
          cc_sm_2: string | null
          channel: string | null
          channel_revised: string | null
          cibil_score: number | null
          current_status: string | null
          customer_name: string | null
          dealer_city: string | null
          dealer_code: number | null
          dealer_name: string | null
          delhi_flag_diy: string | null
          disbursal_date_clean: string | null
          disbursal_datetime: string | null
          disbursal_revised: string | null
          disbursal_timestamp: string | null
          ds_channel: string | null
          ds_roi: number | null
          ds_roi_tla: string | null
          ds_tenure: number | null
          employment_details: string | null
          entry_point: string | null
          final_offer_ltv: number | null
          final_remarks: string | null
          fos_mapping: string | null
          franchise_type: string | null
          fuel_type: string | null
          funnel_loan_state: string | null
          gross_disbursal: number | null
          gross_disbursal_amount: number | null
          hpa_status: string | null
          id: number
          is_lead: number | null
          lead_creation_date: string | null
          lead_date_2: string | null
          lead_date_clean: string | null
          lead_id: string | null
          lead_text: string | null
          li_tenure: number | null
          loan_for_chm: number | null
          loan_for_li: number | null
          loan_for_mi: number | null
          loan_tenure: number | null
          login_date: string | null
          login_date_clean: string | null
          login_date_month: string | null
          make: string | null
          mapping_bi_city: string | null
          model: string | null
          month_col: string | null
          nbfc_channel: string | null
          onboard: string | null
          pf_amount: number | null
          platform_type: string | null
          red_channel_reason: string | null
          red_flag: number | null
          refinance_dealer: string | null
          region: string | null
          registration_no: string | null
          rejection_reason: string | null
          revised_region: string | null
          risk_bucket: string | null
          rm_flow: string | null
          rm_mapping: string | null
          roi_loan_amount: number | null
          roi_per_annum: number | null
          rsa: number | null
          rsm_mapping: string | null
          sm_mapping: string | null
          source: string | null
          system_ltv: number | null
          tl_head: string | null
          tl_mapping: string | null
          tla: string | null
          tnc_accepted_timestamp: string | null
          tnc_generated_date: string | null
          total_loan_sanction: number | null
          unnati: string | null
          valuation_price: number | null
          vas_income_own: number | null
          vas_income_pmax: number | null
          year: number | null
        }
        Insert: {
          approval_date?: string | null
          approval_date_clean?: string | null
          asm_mapping?: string | null
          banking_flag?: string | null
          banking_required?: number | null
          buyback?: number | null
          case_status?: string | null
          case_status_2?: string | null
          cc_fos?: string | null
          cc_fos_2?: string | null
          cc_sm?: string | null
          cc_sm_2?: string | null
          channel?: string | null
          channel_revised?: string | null
          cibil_score?: number | null
          current_status?: string | null
          customer_name?: string | null
          dealer_city?: string | null
          dealer_code?: number | null
          dealer_name?: string | null
          delhi_flag_diy?: string | null
          disbursal_date_clean?: string | null
          disbursal_datetime?: string | null
          disbursal_revised?: string | null
          disbursal_timestamp?: string | null
          ds_channel?: string | null
          ds_roi?: number | null
          ds_roi_tla?: string | null
          ds_tenure?: number | null
          employment_details?: string | null
          entry_point?: string | null
          final_offer_ltv?: number | null
          final_remarks?: string | null
          fos_mapping?: string | null
          franchise_type?: string | null
          fuel_type?: string | null
          funnel_loan_state?: string | null
          gross_disbursal?: number | null
          gross_disbursal_amount?: number | null
          hpa_status?: string | null
          id?: number
          is_lead?: number | null
          lead_creation_date?: string | null
          lead_date_2?: string | null
          lead_date_clean?: string | null
          lead_id?: string | null
          lead_text?: string | null
          li_tenure?: number | null
          loan_for_chm?: number | null
          loan_for_li?: number | null
          loan_for_mi?: number | null
          loan_tenure?: number | null
          login_date?: string | null
          login_date_clean?: string | null
          login_date_month?: string | null
          make?: string | null
          mapping_bi_city?: string | null
          model?: string | null
          month_col?: string | null
          nbfc_channel?: string | null
          onboard?: string | null
          pf_amount?: number | null
          platform_type?: string | null
          red_channel_reason?: string | null
          red_flag?: number | null
          refinance_dealer?: string | null
          region?: string | null
          registration_no?: string | null
          rejection_reason?: string | null
          revised_region?: string | null
          risk_bucket?: string | null
          rm_flow?: string | null
          rm_mapping?: string | null
          roi_loan_amount?: number | null
          roi_per_annum?: number | null
          rsa?: number | null
          rsm_mapping?: string | null
          sm_mapping?: string | null
          source?: string | null
          system_ltv?: number | null
          tl_head?: string | null
          tl_mapping?: string | null
          tla?: string | null
          tnc_accepted_timestamp?: string | null
          tnc_generated_date?: string | null
          total_loan_sanction?: number | null
          unnati?: string | null
          valuation_price?: number | null
          vas_income_own?: number | null
          vas_income_pmax?: number | null
          year?: number | null
        }
        Update: {
          approval_date?: string | null
          approval_date_clean?: string | null
          asm_mapping?: string | null
          banking_flag?: string | null
          banking_required?: number | null
          buyback?: number | null
          case_status?: string | null
          case_status_2?: string | null
          cc_fos?: string | null
          cc_fos_2?: string | null
          cc_sm?: string | null
          cc_sm_2?: string | null
          channel?: string | null
          channel_revised?: string | null
          cibil_score?: number | null
          current_status?: string | null
          customer_name?: string | null
          dealer_city?: string | null
          dealer_code?: number | null
          dealer_name?: string | null
          delhi_flag_diy?: string | null
          disbursal_date_clean?: string | null
          disbursal_datetime?: string | null
          disbursal_revised?: string | null
          disbursal_timestamp?: string | null
          ds_channel?: string | null
          ds_roi?: number | null
          ds_roi_tla?: string | null
          ds_tenure?: number | null
          employment_details?: string | null
          entry_point?: string | null
          final_offer_ltv?: number | null
          final_remarks?: string | null
          fos_mapping?: string | null
          franchise_type?: string | null
          fuel_type?: string | null
          funnel_loan_state?: string | null
          gross_disbursal?: number | null
          gross_disbursal_amount?: number | null
          hpa_status?: string | null
          id?: number
          is_lead?: number | null
          lead_creation_date?: string | null
          lead_date_2?: string | null
          lead_date_clean?: string | null
          lead_id?: string | null
          lead_text?: string | null
          li_tenure?: number | null
          loan_for_chm?: number | null
          loan_for_li?: number | null
          loan_for_mi?: number | null
          loan_tenure?: number | null
          login_date?: string | null
          login_date_clean?: string | null
          login_date_month?: string | null
          make?: string | null
          mapping_bi_city?: string | null
          model?: string | null
          month_col?: string | null
          nbfc_channel?: string | null
          onboard?: string | null
          pf_amount?: number | null
          platform_type?: string | null
          red_channel_reason?: string | null
          red_flag?: number | null
          refinance_dealer?: string | null
          region?: string | null
          registration_no?: string | null
          rejection_reason?: string | null
          revised_region?: string | null
          risk_bucket?: string | null
          rm_flow?: string | null
          rm_mapping?: string | null
          roi_loan_amount?: number | null
          roi_per_annum?: number | null
          rsa?: number | null
          rsm_mapping?: string | null
          sm_mapping?: string | null
          source?: string | null
          system_ltv?: number | null
          tl_head?: string | null
          tl_mapping?: string | null
          tla?: string | null
          tnc_accepted_timestamp?: string | null
          tnc_generated_date?: string | null
          total_loan_sanction?: number | null
          unnati?: string | null
          valuation_price?: number | null
          vas_income_own?: number | null
          vas_income_pmax?: number | null
          year?: number | null
        }
        Relationships: []
      }
      dealers_master: {
        Row: {
          bank_account_status: string | null
          dcf_onboarded: string | null
          dcf_onboarding_date: string | null
          dealer_city: string | null
          dealer_code: number | null
          dealer_name: string | null
          dealer_region: string | null
          email: string | null
          growth_dealer_region: string | null
          id: number
          is_top: boolean
          kam_id: string | null
          latitude: number | null
          longitude: number | null
          onboarding_status: string | null
          phone: string | null
          segment: string | null
          sell_onboarded: string | null
          sell_onboarding_date: string | null
          source: string | null
          status: string | null
          tl_id: string | null
        }
        Insert: {
          bank_account_status?: string | null
          dcf_onboarded?: string | null
          dcf_onboarding_date?: string | null
          dealer_city?: string | null
          dealer_code?: number | null
          dealer_name?: string | null
          dealer_region?: string | null
          email?: string | null
          growth_dealer_region?: string | null
          id?: number
          is_top?: boolean
          kam_id?: string | null
          latitude?: number | null
          longitude?: number | null
          onboarding_status?: string | null
          phone?: string | null
          segment?: string | null
          sell_onboarded?: string | null
          sell_onboarding_date?: string | null
          source?: string | null
          status?: string | null
          tl_id?: string | null
        }
        Update: {
          bank_account_status?: string | null
          dcf_onboarded?: string | null
          dcf_onboarding_date?: string | null
          dealer_city?: string | null
          dealer_code?: number | null
          dealer_name?: string | null
          dealer_region?: string | null
          email?: string | null
          growth_dealer_region?: string | null
          id?: number
          is_top?: boolean
          kam_id?: string | null
          latitude?: number | null
          longitude?: number | null
          onboarding_status?: string | null
          phone?: string | null
          segment?: string | null
          sell_onboarded?: string | null
          sell_onboarding_date?: string | null
          source?: string | null
          status?: string | null
          tl_id?: string | null
        }
        Relationships: []
      }
      export_log: {
        Row: {
          actor_id: string
          actor_name: string | null
          created_at: string
          entity: string
          export_id: string
          filters: Json | null
          row_count: number | null
          selected_fields: Json | null
        }
        Insert: {
          actor_id: string
          actor_name?: string | null
          created_at?: string
          entity: string
          export_id?: string
          filters?: Json | null
          row_count?: number | null
          selected_fields?: Json | null
        }
        Update: {
          actor_id?: string
          actor_name?: string | null
          created_at?: string
          entity?: string
          export_id?: string
          filters?: Json | null
          row_count?: number | null
          selected_fields?: Json | null
        }
        Relationships: []
      }
      incentive_rules: {
        Row: {
          created_at: string | null
          effective_from: string | null
          effective_to: string | null
          metric_key: string
          payout: number | null
          rule_id: string
          scope: string | null
          threshold: number | null
        }
        Insert: {
          created_at?: string | null
          effective_from?: string | null
          effective_to?: string | null
          metric_key: string
          payout?: number | null
          rule_id?: string
          scope?: string | null
          threshold?: number | null
        }
        Update: {
          created_at?: string | null
          effective_from?: string | null
          effective_to?: string | null
          metric_key?: string
          payout?: number | null
          rule_id?: string
          scope?: string | null
          threshold?: number | null
        }
        Relationships: []
      }
      incentive_slabs: {
        Row: {
          created_at: string
          description: string | null
          effective_from: string
          effective_to: string | null
          max_percent: number | null
          min_percent: number
          rate_per_si: number
          role: string
          slab_id: string
          slab_name: string
          updated_at: string
        }
        Insert: {
          created_at?: string
          description?: string | null
          effective_from: string
          effective_to?: string | null
          max_percent?: number | null
          min_percent: number
          rate_per_si: number
          role: string
          slab_id: string
          slab_name: string
          updated_at?: string
        }
        Update: {
          created_at?: string
          description?: string | null
          effective_from?: string
          effective_to?: string | null
          max_percent?: number | null
          min_percent?: number
          rate_per_si?: number
          role?: string
          slab_id?: string
          slab_name?: string
          updated_at?: string
        }
        Relationships: []
      }
      kpi_targets: {
        Row: {
          created_at: string | null
          description: string | null
          effective_from: string
          effective_to: string | null
          id: number
          metric_key: string
          role: string
          target_value: number
        }
        Insert: {
          created_at?: string | null
          description?: string | null
          effective_from?: string
          effective_to?: string | null
          id?: number
          metric_key: string
          role: string
          target_value: number
        }
        Update: {
          created_at?: string | null
          description?: string | null
          effective_from?: string
          effective_to?: string | null
          id?: number
          metric_key?: string
          role?: string
          target_value?: number
        }
        Relationships: []
      }
      location_requests: {
        Row: {
          created_at: string
          dealer_id: string
          decided_at: string | null
          decided_by: string | null
          new_lat: number
          new_lng: number
          old_lat: number | null
          old_lng: number | null
          reason: string | null
          rejection_reason: string | null
          request_id: string
          requested_by: string
          status: string
          updated_at: string
        }
        Insert: {
          created_at?: string
          dealer_id: string
          decided_at?: string | null
          decided_by?: string | null
          new_lat: number
          new_lng: number
          old_lat?: number | null
          old_lng?: number | null
          reason?: string | null
          rejection_reason?: string | null
          request_id: string
          requested_by: string
          status?: string
          updated_at?: string
        }
        Update: {
          created_at?: string
          dealer_id?: string
          decided_at?: string | null
          decided_by?: string | null
          new_lat?: number
          new_lng?: number
          old_lat?: number | null
          old_lng?: number | null
          reason?: string | null
          rejection_reason?: string | null
          request_id?: string
          requested_by?: string
          status?: string
          updated_at?: string
        }
        Relationships: []
      }
      metric_definitions: {
        Row: {
          calc_type: string
          created_at: string
          default_time_scope: string | null
          deprecated_at: string | null
          description: string | null
          dimensions_allowed: string[] | null
          display_name: string
          enabled: boolean
          filters_allowed: string[] | null
          format_pattern: string | null
          gate_threshold: number | null
          has_target: boolean | null
          metric_key: string
          rag_thresholds: Json | null
          sql_template: string
          target_source: string | null
          unit: string
          updated_at: string
          updated_by: string | null
        }
        Insert: {
          calc_type: string
          created_at?: string
          default_time_scope?: string | null
          deprecated_at?: string | null
          description?: string | null
          dimensions_allowed?: string[] | null
          display_name: string
          enabled?: boolean
          filters_allowed?: string[] | null
          format_pattern?: string | null
          gate_threshold?: number | null
          has_target?: boolean | null
          metric_key: string
          rag_thresholds?: Json | null
          sql_template: string
          target_source?: string | null
          unit?: string
          updated_at?: string
          updated_by?: string | null
        }
        Update: {
          calc_type?: string
          created_at?: string
          default_time_scope?: string | null
          deprecated_at?: string | null
          description?: string | null
          dimensions_allowed?: string[] | null
          display_name?: string
          enabled?: boolean
          filters_allowed?: string[] | null
          format_pattern?: string | null
          gate_threshold?: number | null
          has_target?: boolean | null
          metric_key?: string
          rag_thresholds?: Json | null
          sql_template?: string
          target_source?: string | null
          unit?: string
          updated_at?: string
          updated_by?: string | null
        }
        Relationships: []
      }
      sell_leads_master: {
        Row: {
          ans_flag: number | null
          appointment_id: number | null
          appointment_status: string | null
          b2b_flag: number | null
          bid_amount: number | null
          c2b_eligible_insp: number | null
          c2d_ocb_flag: number | null
          c2d_offline_stockin: number | null
          c2d_offline_token: number | null
          c2d_stockin_date: string | null
          cancellation_losses: number | null
          create_offer: number | null
          current_appt_date: string | null
          cx_reg_no: string | null
          deal_creation_date: string | null
          dealer_code: number | null
          dealer_region: string | null
          dl_rank: number | null
          dl_status: string | null
          dl_type: string | null
          elite_flag: number | null
          final_c2d_si_date: string | null
          final_c2dtoken_date: string | null
          final_si_date: string | null
          final_token_date: string | null
          first_cancellation_date: string | null
          first_cancellation_flag: number | null
          franchise_flag: number | null
          full_assist: number | null
          gfd: number | null
          growth_dealer_region: string | null
          growth_inspecting_region: string | null
          growth_zone: string | null
          gs_flag: number | null
          id: number
          im_raised: number | null
          inspection_city: string | null
          inspection_date: string | null
          inspection_done: number | null
          inspection_done_time: string | null
          inspection_region: string | null
          inspection_store: string | null
          latest_c24q: number | null
          latest_c2d_ocb_raise_date: string | null
          latest_ocb_raisedat: number | null
          lead_date: string | null
          lead_expired: number | null
          lead_id: number | null
          lead_purchase_time: string | null
          lead_purchased: number | null
          lead_purchased_date: string | null
          leadprice: number | null
          leadpurchase_price: number | null
          make: string | null
          max_c24_quote: number | null
          model: string | null
          nego_leads: number | null
          ocb_run_count: number | null
          original_appt_date: string | null
          payment_done: number | null
          payment_initiated: number | null
          payment_option_selected: number | null
          product_appt_id: number | null
          refund_time: string | null
          refunded: number | null
          refunded_at: string | null
          reg_appt_rank: number | null
          reg_insp_rank: number | null
          reg_stockin_rank: number | null
          reg_token_rank: number | null
          self_bought_flag: number | null
          self_pay: number | null
          seller_token: number | null
          seller_token_date: string | null
          seller_token_time: string | null
          selleragreedprice: number | null
          sof_flag: number | null
          stock_out_date: string | null
          stockin_date: string | null
          stockins: number | null
          target_price: number | null
          token_date: string | null
          variant: string | null
          verified: string | null
          vertical: string | null
          year: number | null
        }
        Insert: {
          ans_flag?: number | null
          appointment_id?: number | null
          appointment_status?: string | null
          b2b_flag?: number | null
          bid_amount?: number | null
          c2b_eligible_insp?: number | null
          c2d_ocb_flag?: number | null
          c2d_offline_stockin?: number | null
          c2d_offline_token?: number | null
          c2d_stockin_date?: string | null
          cancellation_losses?: number | null
          create_offer?: number | null
          current_appt_date?: string | null
          cx_reg_no?: string | null
          deal_creation_date?: string | null
          dealer_code?: number | null
          dealer_region?: string | null
          dl_rank?: number | null
          dl_status?: string | null
          dl_type?: string | null
          elite_flag?: number | null
          final_c2d_si_date?: string | null
          final_c2dtoken_date?: string | null
          final_si_date?: string | null
          final_token_date?: string | null
          first_cancellation_date?: string | null
          first_cancellation_flag?: number | null
          franchise_flag?: number | null
          full_assist?: number | null
          gfd?: number | null
          growth_dealer_region?: string | null
          growth_inspecting_region?: string | null
          growth_zone?: string | null
          gs_flag?: number | null
          id?: number
          im_raised?: number | null
          inspection_city?: string | null
          inspection_date?: string | null
          inspection_done?: number | null
          inspection_done_time?: string | null
          inspection_region?: string | null
          inspection_store?: string | null
          latest_c24q?: number | null
          latest_c2d_ocb_raise_date?: string | null
          latest_ocb_raisedat?: number | null
          lead_date?: string | null
          lead_expired?: number | null
          lead_id?: number | null
          lead_purchase_time?: string | null
          lead_purchased?: number | null
          lead_purchased_date?: string | null
          leadprice?: number | null
          leadpurchase_price?: number | null
          make?: string | null
          max_c24_quote?: number | null
          model?: string | null
          nego_leads?: number | null
          ocb_run_count?: number | null
          original_appt_date?: string | null
          payment_done?: number | null
          payment_initiated?: number | null
          payment_option_selected?: number | null
          product_appt_id?: number | null
          refund_time?: string | null
          refunded?: number | null
          refunded_at?: string | null
          reg_appt_rank?: number | null
          reg_insp_rank?: number | null
          reg_stockin_rank?: number | null
          reg_token_rank?: number | null
          self_bought_flag?: number | null
          self_pay?: number | null
          seller_token?: number | null
          seller_token_date?: string | null
          seller_token_time?: string | null
          selleragreedprice?: number | null
          sof_flag?: number | null
          stock_out_date?: string | null
          stockin_date?: string | null
          stockins?: number | null
          target_price?: number | null
          token_date?: string | null
          variant?: string | null
          verified?: string | null
          vertical?: string | null
          year?: number | null
        }
        Update: {
          ans_flag?: number | null
          appointment_id?: number | null
          appointment_status?: string | null
          b2b_flag?: number | null
          bid_amount?: number | null
          c2b_eligible_insp?: number | null
          c2d_ocb_flag?: number | null
          c2d_offline_stockin?: number | null
          c2d_offline_token?: number | null
          c2d_stockin_date?: string | null
          cancellation_losses?: number | null
          create_offer?: number | null
          current_appt_date?: string | null
          cx_reg_no?: string | null
          deal_creation_date?: string | null
          dealer_code?: number | null
          dealer_region?: string | null
          dl_rank?: number | null
          dl_status?: string | null
          dl_type?: string | null
          elite_flag?: number | null
          final_c2d_si_date?: string | null
          final_c2dtoken_date?: string | null
          final_si_date?: string | null
          final_token_date?: string | null
          first_cancellation_date?: string | null
          first_cancellation_flag?: number | null
          franchise_flag?: number | null
          full_assist?: number | null
          gfd?: number | null
          growth_dealer_region?: string | null
          growth_inspecting_region?: string | null
          growth_zone?: string | null
          gs_flag?: number | null
          id?: number
          im_raised?: number | null
          inspection_city?: string | null
          inspection_date?: string | null
          inspection_done?: number | null
          inspection_done_time?: string | null
          inspection_region?: string | null
          inspection_store?: string | null
          latest_c24q?: number | null
          latest_c2d_ocb_raise_date?: string | null
          latest_ocb_raisedat?: number | null
          lead_date?: string | null
          lead_expired?: number | null
          lead_id?: number | null
          lead_purchase_time?: string | null
          lead_purchased?: number | null
          lead_purchased_date?: string | null
          leadprice?: number | null
          leadpurchase_price?: number | null
          make?: string | null
          max_c24_quote?: number | null
          model?: string | null
          nego_leads?: number | null
          ocb_run_count?: number | null
          original_appt_date?: string | null
          payment_done?: number | null
          payment_initiated?: number | null
          payment_option_selected?: number | null
          product_appt_id?: number | null
          refund_time?: string | null
          refunded?: number | null
          refunded_at?: string | null
          reg_appt_rank?: number | null
          reg_insp_rank?: number | null
          reg_stockin_rank?: number | null
          reg_token_rank?: number | null
          self_bought_flag?: number | null
          self_pay?: number | null
          seller_token?: number | null
          seller_token_date?: string | null
          seller_token_time?: string | null
          selleragreedprice?: number | null
          sof_flag?: number | null
          stock_out_date?: string | null
          stockin_date?: string | null
          stockins?: number | null
          target_price?: number | null
          token_date?: string | null
          variant?: string | null
          verified?: string | null
          vertical?: string | null
          year?: number | null
        }
        Relationships: []
      }
      signup_requests: {
        Row: {
          city: string | null
          created_at: string | null
          email: string
          id: string
          name: string
          phone: string | null
          region: string | null
          rejected_reason: string | null
          reviewed_at: string | null
          reviewed_by: string | null
          role: string
          status: string
        }
        Insert: {
          city?: string | null
          created_at?: string | null
          email: string
          id?: string
          name: string
          phone?: string | null
          region?: string | null
          rejected_reason?: string | null
          reviewed_at?: string | null
          reviewed_by?: string | null
          role?: string
          status?: string
        }
        Update: {
          city?: string | null
          created_at?: string | null
          email?: string
          id?: string
          name?: string
          phone?: string | null
          region?: string | null
          rejected_reason?: string | null
          reviewed_at?: string | null
          reviewed_by?: string | null
          role?: string
          status?: string
        }
        Relationships: [
          {
            foreignKeyName: "signup_requests_reviewed_by_fkey"
            columns: ["reviewed_by"]
            isOneToOne: false
            referencedRelation: "users"
            referencedColumns: ["user_id"]
          },
        ]
      }
      targets: {
        Row: {
          call_target: number
          created_at: string
          dcf_disbursals_target: number | null
          dcf_gmv_target_lakhs: number | null
          dcf_leads_target: number | null
          dcf_onboarding_target: number | null
          i2si_target: number | null
          input_score_gate: number | null
          month: string
          quality_score_gate: number | null
          role: string
          si_target: number
          target_id: string
          updated_at: string
          updated_by: string | null
          user_id: string
          visit_target: number
        }
        Insert: {
          call_target?: number
          created_at?: string
          dcf_disbursals_target?: number | null
          dcf_gmv_target_lakhs?: number | null
          dcf_leads_target?: number | null
          dcf_onboarding_target?: number | null
          i2si_target?: number | null
          input_score_gate?: number | null
          month: string
          quality_score_gate?: number | null
          role: string
          si_target?: number
          target_id: string
          updated_at?: string
          updated_by?: string | null
          user_id: string
          visit_target?: number
        }
        Update: {
          call_target?: number
          created_at?: string
          dcf_disbursals_target?: number | null
          dcf_gmv_target_lakhs?: number | null
          dcf_leads_target?: number | null
          dcf_onboarding_target?: number | null
          i2si_target?: number | null
          input_score_gate?: number | null
          month?: string
          quality_score_gate?: number | null
          role?: string
          si_target?: number
          target_id?: string
          updated_at?: string
          updated_by?: string | null
          user_id?: string
          visit_target?: number
        }
        Relationships: []
      }
      teams: {
        Row: {
          city: string | null
          region: string | null
          team_id: string
          team_name: string
          tl_user_id: string | null
        }
        Insert: {
          city?: string | null
          region?: string | null
          team_id?: string
          team_name: string
          tl_user_id?: string | null
        }
        Update: {
          city?: string | null
          region?: string | null
          team_id?: string
          team_name?: string
          tl_user_id?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "fk_teams_tl"
            columns: ["tl_user_id"]
            isOneToOne: false
            referencedRelation: "users"
            referencedColumns: ["user_id"]
          },
        ]
      }
      untagged_dealers: {
        Row: {
          address: string | null
          city: string | null
          created_at: string | null
          created_by: string | null
          id: string
          name: string | null
          notes: string | null
          phone: string
          region: string | null
          updated_at: string | null
        }
        Insert: {
          address?: string | null
          city?: string | null
          created_at?: string | null
          created_by?: string | null
          id: string
          name?: string | null
          notes?: string | null
          phone: string
          region?: string | null
          updated_at?: string | null
        }
        Update: {
          address?: string | null
          city?: string | null
          created_at?: string | null
          created_by?: string | null
          id?: string
          name?: string | null
          notes?: string | null
          phone?: string
          region?: string | null
          updated_at?: string | null
        }
        Relationships: []
      }
      users: {
        Row: {
          active: boolean | null
          city: string | null
          created_at: string | null
          deactivated_at: string | null
          deactivated_by: string | null
          email: string | null
          must_reset_password: boolean
          name: string
          phone: string | null
          region: string | null
          role: Database["public"]["Enums"]["user_role"]
          team_id: string | null
          updated_at: string | null
          user_id: string
        }
        Insert: {
          active?: boolean | null
          city?: string | null
          created_at?: string | null
          deactivated_at?: string | null
          deactivated_by?: string | null
          email?: string | null
          must_reset_password?: boolean
          name: string
          phone?: string | null
          region?: string | null
          role?: Database["public"]["Enums"]["user_role"]
          team_id?: string | null
          updated_at?: string | null
          user_id: string
        }
        Update: {
          active?: boolean | null
          city?: string | null
          created_at?: string | null
          deactivated_at?: string | null
          deactivated_by?: string | null
          email?: string | null
          must_reset_password?: boolean
          name?: string
          phone?: string | null
          region?: string | null
          role?: Database["public"]["Enums"]["user_role"]
          team_id?: string | null
          updated_at?: string | null
          user_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "users_team_id_fkey"
            columns: ["team_id"]
            isOneToOne: false
            referencedRelation: "teams"
            referencedColumns: ["team_id"]
          },
        ]
      }
      visits: {
        Row: {
          check_in_at: string | null
          check_out_at: string | null
          created_at: string | null
          dealer_code: number | null
          dealer_id: string | null
          dealer_type: string | null
          distance_from_dealer: number | null
          duration_minutes: number | null
          feedback_data: Json | null
          geo_lat: number | null
          geo_lng: number | null
          is_productive: boolean | null
          kam_id: string | null
          lead_id: string | null
          notes: string | null
          outcome_code: string | null
          photos: string[] | null
          scheduled_at: string
          status: string | null
          untagged_dealer_id: string | null
          updated_at: string | null
          visit_id: string
          visit_type: string | null
        }
        Insert: {
          check_in_at?: string | null
          check_out_at?: string | null
          created_at?: string | null
          dealer_code?: number | null
          dealer_id?: string | null
          dealer_type?: string | null
          distance_from_dealer?: number | null
          duration_minutes?: number | null
          feedback_data?: Json | null
          geo_lat?: number | null
          geo_lng?: number | null
          is_productive?: boolean | null
          kam_id?: string | null
          lead_id?: string | null
          notes?: string | null
          outcome_code?: string | null
          photos?: string[] | null
          scheduled_at: string
          status?: string | null
          untagged_dealer_id?: string | null
          updated_at?: string | null
          visit_id?: string
          visit_type?: string | null
        }
        Update: {
          check_in_at?: string | null
          check_out_at?: string | null
          created_at?: string | null
          dealer_code?: number | null
          dealer_id?: string | null
          dealer_type?: string | null
          distance_from_dealer?: number | null
          duration_minutes?: number | null
          feedback_data?: Json | null
          geo_lat?: number | null
          geo_lng?: number | null
          is_productive?: boolean | null
          kam_id?: string | null
          lead_id?: string | null
          notes?: string | null
          outcome_code?: string | null
          photos?: string[] | null
          scheduled_at?: string
          status?: string | null
          untagged_dealer_id?: string | null
          updated_at?: string | null
          visit_id?: string
          visit_type?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "visits_untagged_dealer_id_fkey"
            columns: ["untagged_dealer_id"]
            isOneToOne: false
            referencedRelation: "untagged_dealers"
            referencedColumns: ["id"]
          },
        ]
      }
    }
    Views: {
      [_ in never]: never
    }
    Functions: {
      exec_raw_sql: { Args: { sql_text: string }; Returns: undefined }
      get_auth_user_role: {
        Args: never
        Returns: Database["public"]["Enums"]["user_role"]
      }
      process_dealers_raw: { Args: never; Returns: undefined }
    }
    Enums: {
      dcf_stage:
        | "created"
        | "in_progress"
        | "approved"
        | "rejected"
        | "disbursed"
      user_role: "KAM" | "TL" | "ADMIN" | "SUPER_ADMIN"
    }
    CompositeTypes: {
      [_ in never]: never
    }
  }
}

type DatabaseWithoutInternals = Omit<Database, "__InternalSupabase">

type DefaultSchema = DatabaseWithoutInternals[Extract<keyof Database, "public">]

export type Tables<
  DefaultSchemaTableNameOrOptions extends
    | keyof (DefaultSchema["Tables"] & DefaultSchema["Views"])
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof (DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"] &
        DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Views"])
    : never = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? (DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"] &
      DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Views"])[TableName] extends {
      Row: infer R
    }
    ? R
    : never
  : DefaultSchemaTableNameOrOptions extends keyof (DefaultSchema["Tables"] &
        DefaultSchema["Views"])
    ? (DefaultSchema["Tables"] &
        DefaultSchema["Views"])[DefaultSchemaTableNameOrOptions] extends {
        Row: infer R
      }
      ? R
      : never
    : never

export type TablesInsert<
  DefaultSchemaTableNameOrOptions extends
    | keyof DefaultSchema["Tables"]
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"]
    : never = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"][TableName] extends {
      Insert: infer I
    }
    ? I
    : never
  : DefaultSchemaTableNameOrOptions extends keyof DefaultSchema["Tables"]
    ? DefaultSchema["Tables"][DefaultSchemaTableNameOrOptions] extends {
        Insert: infer I
      }
      ? I
      : never
    : never

export type TablesUpdate<
  DefaultSchemaTableNameOrOptions extends
    | keyof DefaultSchema["Tables"]
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"]
    : never = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"][TableName] extends {
      Update: infer U
    }
    ? U
    : never
  : DefaultSchemaTableNameOrOptions extends keyof DefaultSchema["Tables"]
    ? DefaultSchema["Tables"][DefaultSchemaTableNameOrOptions] extends {
        Update: infer U
      }
      ? U
      : never
    : never

export type Enums<
  DefaultSchemaEnumNameOrOptions extends
    | keyof DefaultSchema["Enums"]
    | { schema: keyof DatabaseWithoutInternals },
  EnumName extends DefaultSchemaEnumNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaEnumNameOrOptions["schema"]]["Enums"]
    : never = never,
> = DefaultSchemaEnumNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[DefaultSchemaEnumNameOrOptions["schema"]]["Enums"][EnumName]
  : DefaultSchemaEnumNameOrOptions extends keyof DefaultSchema["Enums"]
    ? DefaultSchema["Enums"][DefaultSchemaEnumNameOrOptions]
    : never

export type CompositeTypes<
  PublicCompositeTypeNameOrOptions extends
    | keyof DefaultSchema["CompositeTypes"]
    | { schema: keyof DatabaseWithoutInternals },
  CompositeTypeName extends PublicCompositeTypeNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[PublicCompositeTypeNameOrOptions["schema"]]["CompositeTypes"]
    : never = never,
> = PublicCompositeTypeNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[PublicCompositeTypeNameOrOptions["schema"]]["CompositeTypes"][CompositeTypeName]
  : PublicCompositeTypeNameOrOptions extends keyof DefaultSchema["CompositeTypes"]
    ? DefaultSchema["CompositeTypes"][PublicCompositeTypeNameOrOptions]
    : never

export const Constants = {
  public: {
    Enums: {
      dcf_stage: [
        "created",
        "in_progress",
        "approved",
        "rejected",
        "disbursed",
      ],
      user_role: ["KAM", "TL", "ADMIN", "SUPER_ADMIN"],
    },
  },
} as const
